// <auto-generated />
using System;
using CoursesUIT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoursesUIT.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240402085259_LMT")]
    partial class LMT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoursesUIT.Models.Courses", b =>
                {
                    b.Property<Guid?>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("9250d994-2557-4573-8465-417248667051"),
                            CourseName = "Toán",
                            Description = "IT thì nên giỏi toán:))"
                        },
                        new
                        {
                            CourseId = new Guid("88738493-3a75-4443-8f6a-313453432192"),
                            CourseName = "Văn",
                            Description = "Tao văn trên 5 là ok rồi"
                        });
                });

            modelBuilder.Entity("CoursesUIT.Models.CoursesUIT", b =>
                {
                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoursesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentId", "CoursesId");

                    b.HasIndex("CoursesId");

                    b.ToTable("CoursesUIT");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("e2397972-8743-431a-9482-60292f08320f"),
                            CoursesId = new Guid("88738493-3a75-4443-8f6a-313453432192")
                        },
                        new
                        {
                            StudentId = new Guid("4e79044a-988d-4488-97b7-3e474e4340e2"),
                            CoursesId = new Guid("9250d994-2557-4573-8465-417248667051")
                        });
                });

            modelBuilder.Entity("CoursesUIT.Models.Student", b =>
                {
                    b.Property<Guid?>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("e2397972-8743-431a-9482-60292f08320f"),
                            Name = "Lê Minh Tài"
                        },
                        new
                        {
                            StudentId = new Guid("4e79044a-988d-4488-97b7-3e474e4340e2"),
                            Name = "x TheSpectre x"
                        });
                });

            modelBuilder.Entity("CoursesUIT.Models.CoursesUIT", b =>
                {
                    b.HasOne("CoursesUIT.Models.Courses", "Courses")
                        .WithMany("CoursesUIT")
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoursesUIT.Models.Student", "Student")
                        .WithMany("CoursesUIT")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CoursesUIT.Models.Courses", b =>
                {
                    b.Navigation("CoursesUIT");
                });

            modelBuilder.Entity("CoursesUIT.Models.Student", b =>
                {
                    b.Navigation("CoursesUIT");
                });
#pragma warning restore 612, 618
        }
    }
}
